# Generated by Django 3.0.6 on 2020-07-26 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessmentparameter',
            fields=[
                ('idassessmentparameter', models.AutoField(db_column='idAssessmentParameter', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AssessmentParameter',
                'ordering': ['idassessmentparameter'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('idconcept', models.AutoField(db_column='idConcept', primary_key=True, serialize=False)),
                ('nameconcept', models.CharField(db_column='nameConcept', max_length=100)),
                ('fk_idconcept', models.BigIntegerField(blank=True, db_column='fk_idConcept', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'Concept',
                'ordering': ['idconcept'],
            },
        ),
        migrations.CreateModel(
            name='Informationitem',
            fields=[
                ('idinformationitem', models.AutoField(db_column='idInformationItem', primary_key=True, serialize=False)),
                ('nameinformationitem', models.CharField(blank=True, db_column='nameInformationItem', max_length=256, null=True)),
                ('descriptioninformationitem', models.TextField(blank=True, db_column='descriptionInformationItem', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idconcept', models.ForeignKey(db_column='fk_idConcept', on_delete=django.db.models.deletion.CASCADE, related_name='informationitems', to='core.Concept')),
            ],
            options={
                'db_table': 'InformationItem',
                'ordering': ['idinformationitem'],
            },
        ),
        migrations.CreateModel(
            name='Informationitemtype',
            fields=[
                ('idinformationitemtype', models.AutoField(db_column='idInformationItemType', primary_key=True, serialize=False)),
                ('nameinformationitemtype', models.CharField(db_column='nameInformationItemType', max_length=256)),
            ],
            options={
                'db_table': 'InformationItemType',
            },
        ),
        migrations.CreateModel(
            name='Instrucelementtype',
            fields=[
                ('idinstrucelementtype', models.AutoField(db_column='idInstrucElementType', primary_key=True, serialize=False)),
                ('nameinstrucelementtype', models.CharField(db_column='nameInstrucElementType', max_length=256)),
                ('idcategory', models.BigIntegerField(blank=True, db_column='idCategory', null=True)),
            ],
            options={
                'db_table': 'InstrucElementType',
            },
        ),
        migrations.CreateModel(
            name='Instructionalelement',
            fields=[
                ('idinstructionalelement', models.AutoField(db_column='idInstructionalElement', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='label', max_length=256)),
                ('memberamount', models.BigIntegerField(blank=True, db_column='memberAmount', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idconcept', models.ForeignKey(blank=True, db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Concept')),
            ],
            options={
                'db_table': 'InstructionalElement',
                'ordering': ['idinstructionalelement'],
            },
        ),
        migrations.CreateModel(
            name='Knowledgedomain',
            fields=[
                ('idknowledgedomain', models.AutoField(db_column='idKnowledgeDomain', primary_key=True, serialize=False)),
                ('nameknowledgedomain', models.CharField(db_column='nameKnowledgeDomain', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('lastversion', models.CharField(blank=True, db_column='lastVersion', max_length=45, null=True)),
                ('fk_iduser', models.ForeignKey(db_column='fk_idUser', on_delete=django.db.models.deletion.CASCADE, related_name='knowledgedomains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'KnowledgeDomain',
                'ordering': ['idknowledgedomain'],
            },
        ),
        migrations.CreateModel(
            name='Mediatype',
            fields=[
                ('idmediatype', models.AutoField(db_column='idMediaType', primary_key=True, serialize=False)),
                ('namemediatype', models.CharField(blank=True, db_column='nameMediaType', max_length=256)),
            ],
            options={
                'db_table': 'MediaType',
            },
        ),
        migrations.CreateModel(
            name='Priorlevel',
            fields=[
                ('idpriorlevel', models.AutoField(db_column='idPriorLevel', primary_key=True, serialize=False)),
                ('typepriorlevel', models.CharField(db_column='typePriorLevel', max_length=256)),
            ],
            options={
                'db_table': 'PriorLevel',
                'ordering': ['idpriorlevel'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.AutoField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('descriptionquestion', models.TextField(db_column='descriptionQuestion')),
                ('orderquestion', models.IntegerField(blank=True, db_column='orderQuestion', null=True)),
                ('fk_idinstructionalelement', models.ForeignKey(blank=True, db_column='fk_idInstructionalElement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Instructionalelement')),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['orderquestion'],
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('idquestiontype', models.AutoField(db_column='idQuestionType', primary_key=True, serialize=False)),
                ('namequestiontype', models.CharField(db_column='nameQuestionType', max_length=256)),
            ],
            options={
                'db_table': 'QuestionType',
            },
        ),
        migrations.CreateModel(
            name='Referencetype',
            fields=[
                ('idreferencetype', models.AutoField(db_column='idReferenceType', primary_key=True, serialize=False)),
                ('namererefencetype', models.CharField(db_column='nameRerefenceType', max_length=256)),
            ],
            options={
                'db_table': 'Referencetype',
            },
        ),
        migrations.CreateModel(
            name='Scopo',
            fields=[
                ('idscopo', models.AutoField(db_column='idScopo', primary_key=True, serialize=False)),
                ('typescopo', models.CharField(db_column='typeScopo', max_length=256)),
            ],
            options={
                'db_table': 'Scopo',
            },
        ),
        migrations.CreateModel(
            name='Typethreshold',
            fields=[
                ('idtypethreshold', models.AutoField(db_column='idTypeThreshold', primary_key=True, serialize=False)),
                ('nametypethreshold', models.CharField(db_column='nameTypeThreshold', max_length=256)),
            ],
            options={
                'db_table': 'TypeThreshold',
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('idsingle', models.AutoField(db_column='idSingle', primary_key=True, serialize=False)),
                ('threshold', models.CharField(blank=True, db_column='threshold', max_length=256, null=True)),
                ('fk_idassessmentparameter', models.ForeignKey(db_column='fk_idAssessmentParameter', on_delete=django.db.models.deletion.CASCADE, related_name='single', to='core.Assessmentparameter')),
            ],
            options={
                'db_table': 'Single',
            },
        ),
        migrations.CreateModel(
            name='Resolutionquestion',
            fields=[
                ('idresolutionquestion', models.AutoField(db_column='idResolutionQuestion', primary_key=True, serialize=False)),
                ('correctitem', models.TextField(blank=True, db_column='correctItem', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='correctAnswer', null=True)),
                ('fk_idquestion', models.ForeignKey(blank=True, db_column='fk_idQuestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutionquestion', to='core.Question')),
            ],
            options={
                'db_table': 'ResolutionQuestion',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idreference', models.AutoField(db_column='idReference', primary_key=True, serialize=False)),
                ('namereference', models.CharField(blank=True, db_column='nameReference', max_length=256, null=True)),
                ('fk_referencetype', models.ForeignKey(blank=True, db_column='fk_ReferenceType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='referencetype', to='core.Referencetype')),
                ('sourceconcept', models.ForeignKey(db_column='sourceConcept', on_delete=django.db.models.deletion.CASCADE, related_name='sourceconcept', to='core.Concept')),
                ('targetconcept', models.ForeignKey(db_column='targetConcept', on_delete=django.db.models.deletion.CASCADE, related_name='targetconcept', to='core.Concept')),
            ],
            options={
                'db_table': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('idrange', models.AutoField(db_column='idRange', primary_key=True, serialize=False)),
                ('namerange', models.CharField(db_column='nameRange', max_length=256)),
                ('initialvalue', models.IntegerField(db_column='initialValue')),
                ('limitvalue', models.IntegerField(db_column='limitValue')),
                ('fk_idassessmentparameter', models.ForeignKey(db_column='fk_idAssessmentParameter', on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='core.Assessmentparameter')),
            ],
            options={
                'db_table': 'Range',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='typequestion',
            field=models.ForeignKey(db_column='typeQuestion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questiontype'),
        ),
        migrations.CreateModel(
            name='Priorknowledge',
            fields=[
                ('idpriorknowledge', models.AutoField(db_column='idPriorKnowledge', primary_key=True, serialize=False)),
                ('namepriorknowledge', models.CharField(db_column='namePriorKnowledge', max_length=256)),
                ('fk_idconcept', models.ForeignKey(db_column='fk_idConcept', on_delete=django.db.models.deletion.CASCADE, related_name='priorknowledge', to='core.Concept')),
                ('priorlevel', models.ForeignKey(db_column='priorLevel', on_delete=django.db.models.deletion.CASCADE, to='core.Priorlevel')),
            ],
            options={
                'db_table': 'PriorKnowledge',
                'ordering': ['idpriorknowledge'],
            },
        ),
        migrations.CreateModel(
            name='Phaseprocedure',
            fields=[
                ('idphaseprocedure', models.AutoField(db_column='idPhaseProcedure', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='order')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('fk_informationitem', models.ForeignKey(db_column='fk_InformationItem', on_delete=django.db.models.deletion.CASCADE, related_name='phaseprocedures', to='core.Informationitem')),
            ],
            options={
                'db_table': 'PhaseProcedure',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idmodule', models.AutoField(db_column='idModule', primary_key=True, serialize=False)),
                ('namemodule', models.CharField(db_column='nameModule', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idmodule', models.ForeignKey(blank=True, db_column='fk_IdModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.Module')),
                ('idknowledgedomain', models.ForeignKey(blank=True, db_column='idKnowledgeDomain', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.Knowledgedomain')),
            ],
            options={
                'db_table': 'Module',
                'ordering': ['idmodule'],
            },
        ),
        migrations.CreateModel(
            name='Mobilemedia',
            fields=[
                ('idmobilemedia', models.AutoField(db_column='idMobileMedia', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', max_length=256, null=True)),
                ('difficultyLevel', models.IntegerField(blank=True, db_column='difficultyLevel', null=True)),
                ('learningStyle', models.IntegerField(blank=True, db_column='learningStyle', null=True)),
                ('path', models.CharField(blank=True, db_column='path', max_length=256, null=True)),
                ('namefile', models.CharField(blank=True, db_column='nameFile', max_length=256, null=True)),
                ('resolution', models.CharField(blank=True, db_column='resolution', max_length=256, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('time', models.CharField(blank=True, db_column='time', max_length=256, null=True)),
                ('textfull', models.TextField(blank=True, db_column='textFull', null=True)),
                ('textshort', models.TextField(blank=True, db_column='textShort', null=True)),
                ('urllink', models.CharField(blank=True, db_column='url', max_length=256, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idconcept', models.ForeignKey(blank=True, db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Concept')),
                ('fk_idinstructionalelement', models.ForeignKey(blank=True, db_column='fk_idInstructionalElement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Instructionalelement')),
                ('fk_idknowledgedomain', models.ForeignKey(blank=True, db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Knowledgedomain')),
                ('fk_idmediatype', models.ForeignKey(blank=True, db_column='fk_idMediaType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediatype', to='core.Mediatype')),
                ('fk_idphaseprocedure', models.ForeignKey(blank=True, db_column='fk_idPhaseProcedure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Phaseprocedure')),
                ('fk_idquestion', models.ForeignKey(blank=True, db_column='fk_idQuestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Question')),
                ('fk_informationitem', models.ForeignKey(blank=True, db_column='fk_Informationitem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Informationitem')),
                ('fk_module', models.ForeignKey(blank=True, db_column='fk_Module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Module')),
            ],
            options={
                'db_table': 'MobileMedia',
                'ordering': ['idmobilemedia'],
            },
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(blank=True, db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_idmodule',
            field=models.ForeignKey(blank=True, db_column='fk_idModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Module'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_informationitem',
            field=models.ForeignKey(blank=True, db_column='fk_idInformationItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Informationitem'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_instructionalelementtype',
            field=models.ForeignKey(blank=True, db_column='fk_InstructionalElementType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Instrucelementtype'),
        ),
        migrations.AddField(
            model_name='informationitem',
            name='fk_informationitemtype',
            field=models.ForeignKey(db_column='fk_InformationItemType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationitemtypes', to='core.Informationitemtype'),
        ),
        migrations.AddField(
            model_name='concept',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(db_column='fk_idKnowledgeDomain', on_delete=django.db.models.deletion.CASCADE, to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='concept',
            name='fk_idmodule',
            field=models.ForeignKey(db_column='fk_idModule', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.Module'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idconcept',
            field=models.ForeignKey(db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Concept'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idmodule',
            field=models.ForeignKey(db_column='fk_idModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Module'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='scopo',
            field=models.ForeignKey(db_column='scopo', on_delete=django.db.models.deletion.CASCADE, to='core.Scopo'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='typethreshold',
            field=models.ForeignKey(db_column='typeThreshold', on_delete=django.db.models.deletion.CASCADE, to='core.Typethreshold'),
        ),
        migrations.CreateModel(
            name='Answersalternatives',
            fields=[
                ('idanswersalternatives', models.AutoField(db_column='idAnswersAlternatives', primary_key=True, serialize=False)),
                ('idobjanswer', models.CharField(blank=True, db_column='idObjAnswer', max_length=256, null=True)),
                ('answers', models.CharField(db_column='answers', max_length=256)),
                ('istrue', models.BooleanField(db_column='isTrue')),
                ('orderansweralternatives', models.BigIntegerField(blank=True, db_column='orderAnswerAlternatives', null=True)),
                ('fk_idquestion', models.ForeignKey(db_column='fk_idQuestion', on_delete=django.db.models.deletion.CASCADE, related_name='answersalternatives', to='core.Question')),
            ],
            options={
                'db_table': 'AnswersAlternatives',
                'ordering': ['orderansweralternatives'],
            },
        ),
    ]
