<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-08-05 01:28

from django.db import migrations, models
=======
# Generated by Django 3.0.6 on 2020-08-14 15:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0011_update_proxy_permissions'),
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Answersalternatives',
            fields=[
                ('idanswersalternatives', models.AutoField(db_column='idAnswersAlternatives', primary_key=True, serialize=False)),
                ('idobjanswer', models.CharField(blank=True, db_column='idObjAnswer', max_length=256, null=True)),
                ('answers', models.CharField(db_column='answers', max_length=256)),
                ('istrue', models.BooleanField(db_column='isTrue')),
                ('orderansweralternatives', models.BigIntegerField(blank=True, db_column='orderAnswerAlternatives', null=True)),
            ],
            options={
                'db_table': 'AnswersAlternatives',
                'ordering': ['orderansweralternatives'],
                'managed': False,
            },
=======
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
        ),
        migrations.CreateModel(
            name='Assessmentparameter',
            fields=[
                ('idassessmentparameter', models.AutoField(db_column='idAssessmentParameter', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AssessmentParameter',
                'ordering': ['idassessmentparameter'],
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('idconcept', models.AutoField(db_column='idConcept', primary_key=True, serialize=False)),
                ('nameconcept', models.CharField(db_column='nameConcept', max_length=100)),
                ('fk_idconcept', models.BigIntegerField(blank=True, db_column='fk_idConcept', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'Concept',
                'ordering': ['idconcept'],
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Informationitem',
            fields=[
                ('idinformationitem', models.AutoField(db_column='idInformationItem', primary_key=True, serialize=False)),
                ('nameinformationitem', models.CharField(blank=True, db_column='nameInformationItem', max_length=256, null=True)),
                ('descriptioninformationitem', models.TextField(blank=True, db_column='descriptionInformationItem', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
<<<<<<< HEAD
=======
                ('fk_idconcept', models.ForeignKey(db_column='fk_idConcept', on_delete=django.db.models.deletion.CASCADE, related_name='informationitems', to='core.Concept')),
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            ],
            options={
                'db_table': 'InformationItem',
                'ordering': ['idinformationitem'],
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Informationitemtype',
            fields=[
                ('idinformationitemtype', models.AutoField(db_column='idInformationItemType', primary_key=True, serialize=False)),
                ('nameinformationitemtype', models.CharField(db_column='nameInformationItemType', max_length=256)),
            ],
            options={
                'db_table': 'InformationItemType',
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Instrucelementtype',
            fields=[
                ('idinstrucelementtype', models.AutoField(db_column='idInstrucElementType', primary_key=True, serialize=False)),
                ('nameinstrucelementtype', models.CharField(db_column='nameInstrucElementType', max_length=256)),
                ('idcategory', models.BigIntegerField(blank=True, db_column='idCategory', null=True)),
            ],
            options={
                'db_table': 'InstrucElementType',
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Instructionalelement',
            fields=[
                ('idinstructionalelement', models.AutoField(db_column='idInstructionalElement', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='label', max_length=256)),
                ('memberamount', models.BigIntegerField(blank=True, db_column='memberAmount', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
<<<<<<< HEAD
=======
                ('fk_idconcept', models.ForeignKey(blank=True, db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Concept')),
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            ],
            options={
                'db_table': 'InstructionalElement',
                'ordering': ['idinstructionalelement'],
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Knowledgedomain',
            fields=[
                ('idknowledgedomain', models.AutoField(db_column='idKnowledgeDomain', primary_key=True, serialize=False)),
                ('nameknowledgedomain', models.CharField(db_column='nameKnowledgeDomain', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('lastversion', models.CharField(blank=True, db_column='lastVersion', max_length=45, null=True)),
<<<<<<< HEAD
=======
                ('fk_iduser', models.ForeignKey(db_column='fk_idUser', on_delete=django.db.models.deletion.CASCADE, related_name='knowledgedomains', to=settings.AUTH_USER_MODEL)),
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            ],
            options={
                'db_table': 'KnowledgeDomain',
                'ordering': ['idknowledgedomain'],
<<<<<<< HEAD
                'managed': False,
=======
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Mediatype',
            fields=[
                ('idmediatype', models.AutoField(db_column='idMediaType', primary_key=True, serialize=False)),
                ('namemediatype', models.CharField(blank=True, db_column='nameMediaType', max_length=256)),
            ],
            options={
                'db_table': 'MediaType',
<<<<<<< HEAD
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobilemedia',
            fields=[
                ('idmobilemedia', models.AutoField(db_column='idMobileMedia', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', max_length=256, null=True)),
                ('difficultyLevel', models.IntegerField(blank=True, db_column='difficultyLevel', null=True)),
                ('learningStyle', models.IntegerField(blank=True, db_column='learningStyle', null=True)),
                ('path', models.CharField(blank=True, db_column='path', max_length=256, null=True)),
                ('namefile', models.CharField(blank=True, db_column='nameFile', max_length=256, null=True)),
                ('resolution', models.CharField(blank=True, db_column='resolution', max_length=256, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('time', models.CharField(blank=True, db_column='time', max_length=256, null=True)),
                ('textfull', models.TextField(blank=True, db_column='textFull', null=True)),
                ('textshort', models.TextField(blank=True, db_column='textShort', null=True)),
                ('urllink', models.CharField(blank=True, db_column='url', max_length=256, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'MobileMedia',
                'ordering': ['idmobilemedia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idmodule', models.AutoField(db_column='idModule', primary_key=True, serialize=False)),
                ('namemodule', models.CharField(db_column='nameModule', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'Module',
                'ordering': ['idmodule'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phaseprocedure',
            fields=[
                ('idphaseprocedure', models.AutoField(db_column='idPhaseProcedure', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='order')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'PhaseProcedure',
                'ordering': ['order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorknowledge',
            fields=[
                ('idpriorknowledge', models.AutoField(db_column='idPriorKnowledge', primary_key=True, serialize=False)),
                ('namepriorknowledge', models.CharField(db_column='namePriorKnowledge', max_length=256)),
            ],
            options={
                'db_table': 'PriorKnowledge',
                'ordering': ['idpriorknowledge'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorlevel',
            fields=[
                ('idpriorlevel', models.AutoField(db_column='idPriorLevel', primary_key=True, serialize=False)),
                ('typepriorlevel', models.CharField(db_column='typePriorLevel', max_length=256)),
            ],
            options={
                'db_table': 'PriorLevel',
                'ordering': ['idpriorlevel'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.AutoField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('descriptionquestion', models.TextField(db_column='descriptionQuestion')),
                ('orderquestion', models.IntegerField(blank=True, db_column='orderQuestion', null=True)),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['orderquestion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('idquestiontype', models.AutoField(db_column='idQuestionType', primary_key=True, serialize=False)),
                ('namequestiontype', models.CharField(db_column='nameQuestionType', max_length=256)),
            ],
            options={
                'db_table': 'QuestionType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('idrange', models.AutoField(db_column='idRange', primary_key=True, serialize=False)),
                ('namerange', models.CharField(db_column='nameRange', max_length=256)),
                ('initialvalue', models.IntegerField(db_column='initialValue')),
                ('limitvalue', models.IntegerField(db_column='limitValue')),
            ],
            options={
                'db_table': 'Range',
                'managed': False,
=======
            },
        ),
        migrations.CreateModel(
            name='Priorlevel',
            fields=[
                ('idpriorlevel', models.AutoField(db_column='idPriorLevel', primary_key=True, serialize=False)),
                ('typepriorlevel', models.CharField(db_column='typePriorLevel', max_length=256)),
            ],
            options={
                'db_table': 'PriorLevel',
                'ordering': ['idpriorlevel'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.AutoField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('descriptionquestion', models.TextField(db_column='descriptionQuestion')),
                ('orderquestion', models.IntegerField(blank=True, db_column='orderQuestion', null=True)),
                ('fk_idinstructionalelement', models.ForeignKey(blank=True, db_column='fk_idInstructionalElement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Instructionalelement')),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['orderquestion'],
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('idquestiontype', models.AutoField(db_column='idQuestionType', primary_key=True, serialize=False)),
                ('namequestiontype', models.CharField(db_column='nameQuestionType', max_length=256)),
            ],
            options={
                'db_table': 'QuestionType',
            },
        ),
        migrations.CreateModel(
            name='Referencetype',
            fields=[
                ('idreferencetype', models.AutoField(db_column='idReferenceType', primary_key=True, serialize=False)),
                ('namererefencetype', models.CharField(db_column='nameRerefenceType', max_length=256)),
            ],
            options={
                'db_table': 'Referencetype',
            },
        ),
        migrations.CreateModel(
            name='Scopo',
            fields=[
                ('idscopo', models.AutoField(db_column='idScopo', primary_key=True, serialize=False)),
                ('typescopo', models.CharField(db_column='typeScopo', max_length=256)),
            ],
            options={
                'db_table': 'Scopo',
            },
        ),
        migrations.CreateModel(
            name='Typethreshold',
            fields=[
                ('idtypethreshold', models.AutoField(db_column='idTypeThreshold', primary_key=True, serialize=False)),
                ('nametypethreshold', models.CharField(db_column='nameTypeThreshold', max_length=256)),
            ],
            options={
                'db_table': 'TypeThreshold',
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('idsingle', models.AutoField(db_column='idSingle', primary_key=True, serialize=False)),
                ('threshold', models.CharField(blank=True, db_column='threshold', max_length=256, null=True)),
                ('fk_idassessmentparameter', models.ForeignKey(db_column='fk_idAssessmentParameter', on_delete=django.db.models.deletion.CASCADE, related_name='single', to='core.Assessmentparameter')),
            ],
            options={
                'db_table': 'Single',
            },
        ),
        migrations.CreateModel(
            name='Resolutionquestion',
            fields=[
                ('idresolutionquestion', models.AutoField(db_column='idResolutionQuestion', primary_key=True, serialize=False)),
                ('correctitem', models.TextField(blank=True, db_column='correctItem', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='correctAnswer', null=True)),
                ('fk_idquestion', models.ForeignKey(blank=True, db_column='fk_idQuestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutionquestion', to='core.Question')),
            ],
            options={
                'db_table': 'ResolutionQuestion',
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idreference', models.AutoField(db_column='idReference', primary_key=True, serialize=False)),
                ('namereference', models.CharField(blank=True, db_column='nameReference', max_length=256, null=True)),
<<<<<<< HEAD
            ],
            options={
                'db_table': 'Reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencetype',
            fields=[
                ('idreferencetype', models.AutoField(db_column='idReferenceType', primary_key=True, serialize=False)),
                ('namererefencetype', models.CharField(db_column='nameRerefenceType', max_length=256)),
            ],
            options={
                'db_table': 'Referencetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resolutionquestion',
            fields=[
                ('idresolutionquestion', models.AutoField(db_column='idResolutionQuestion', primary_key=True, serialize=False)),
                ('correctitem', models.TextField(blank=True, db_column='correctItem', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='correctAnswer', null=True)),
            ],
            options={
                'db_table': 'ResolutionQuestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scopo',
            fields=[
                ('idscopo', models.AutoField(db_column='idScopo', primary_key=True, serialize=False)),
                ('typescopo', models.CharField(db_column='typeScopo', max_length=256)),
            ],
            options={
                'db_table': 'Scopo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('idsingle', models.AutoField(db_column='idSingle', primary_key=True, serialize=False)),
                ('threshold', models.CharField(blank=True, db_column='threshold', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Single',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typethreshold',
            fields=[
                ('idtypethreshold', models.AutoField(db_column='idTypeThreshold', primary_key=True, serialize=False)),
                ('nametypethreshold', models.CharField(db_column='nameTypeThreshold', max_length=256)),
            ],
            options={
                'db_table': 'TypeThreshold',
                'managed': False,
=======
                ('fk_referencetype', models.ForeignKey(blank=True, db_column='fk_ReferenceType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='referencetype', to='core.Referencetype')),
                ('sourceconcept', models.ForeignKey(db_column='sourceConcept', on_delete=django.db.models.deletion.CASCADE, related_name='sourceconcept', to='core.Concept')),
                ('targetconcept', models.ForeignKey(db_column='targetConcept', on_delete=django.db.models.deletion.CASCADE, related_name='targetconcept', to='core.Concept')),
            ],
            options={
                'db_table': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('idrange', models.AutoField(db_column='idRange', primary_key=True, serialize=False)),
                ('namerange', models.CharField(db_column='nameRange', max_length=256)),
                ('initialvalue', models.IntegerField(db_column='initialValue')),
                ('limitvalue', models.IntegerField(db_column='limitValue')),
                ('fk_idassessmentparameter', models.ForeignKey(db_column='fk_idAssessmentParameter', on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='core.Assessmentparameter')),
            ],
            options={
                'db_table': 'Range',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='typequestion',
            field=models.ForeignKey(db_column='typeQuestion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questiontype'),
        ),
        migrations.CreateModel(
            name='Priorknowledge',
            fields=[
                ('idpriorknowledge', models.AutoField(db_column='idPriorKnowledge', primary_key=True, serialize=False)),
                ('namepriorknowledge', models.CharField(db_column='namePriorKnowledge', max_length=256)),
                ('fk_priorsourceconcept', models.ForeignKey(db_column='fk_priorSourceConcept', on_delete=django.db.models.deletion.CASCADE, related_name='priorknowledge', to='core.Concept')),
                ('fk_priortargetconcept', models.ForeignKey(db_column='fk_priorTargetConcept', on_delete=django.db.models.deletion.CASCADE, related_name='targetpriorknowledge', to='core.Concept')),
                ('priorlevel', models.ForeignKey(db_column='priorLevel', on_delete=django.db.models.deletion.CASCADE, to='core.Priorlevel')),
            ],
            options={
                'db_table': 'PriorKnowledge',
                'ordering': ['idpriorknowledge'],
            },
        ),
        migrations.CreateModel(
            name='Phaseprocedure',
            fields=[
                ('idphaseprocedure', models.AutoField(db_column='idPhaseProcedure', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='order')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('fk_informationitem', models.ForeignKey(db_column='fk_InformationItem', on_delete=django.db.models.deletion.CASCADE, related_name='phaseprocedures', to='core.Informationitem')),
            ],
            options={
                'db_table': 'PhaseProcedure',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idmodule', models.AutoField(db_column='idModule', primary_key=True, serialize=False)),
                ('namemodule', models.CharField(db_column='nameModule', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idmodule', models.ForeignKey(blank=True, db_column='fk_IdModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.Module')),
                ('idknowledgedomain', models.ForeignKey(blank=True, db_column='idKnowledgeDomain', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.Knowledgedomain')),
            ],
            options={
                'db_table': 'Module',
                'ordering': ['idmodule'],
            },
        ),
        migrations.CreateModel(
            name='Mobilemedia',
            fields=[
                ('idmobilemedia', models.AutoField(db_column='idMobileMedia', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', max_length=256, null=True)),
                ('difficultyLevel', models.IntegerField(blank=True, db_column='difficultyLevel', null=True)),
                ('learningStyle', models.IntegerField(blank=True, db_column='learningStyle', null=True)),
                ('path', models.CharField(blank=True, db_column='path', max_length=256, null=True)),
                ('namefile', models.CharField(blank=True, db_column='nameFile', max_length=256, null=True)),
                ('resolution', models.CharField(blank=True, db_column='resolution', max_length=256, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('time', models.CharField(blank=True, db_column='time', max_length=256, null=True)),
                ('textfull', models.TextField(blank=True, db_column='textFull', null=True)),
                ('textshort', models.TextField(blank=True, db_column='textShort', null=True)),
                ('urllink', models.CharField(blank=True, db_column='url', max_length=256, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
                ('fk_idconcept', models.ForeignKey(blank=True, db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Concept')),
                ('fk_idinstructionalelement', models.ForeignKey(blank=True, db_column='fk_idInstructionalElement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Instructionalelement')),
                ('fk_idknowledgedomain', models.ForeignKey(blank=True, db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Knowledgedomain')),
                ('fk_idmediatype', models.ForeignKey(blank=True, db_column='fk_idMediaType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mediatype', to='core.Mediatype')),
                ('fk_idphaseprocedure', models.ForeignKey(blank=True, db_column='fk_idPhaseProcedure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Phaseprocedure')),
                ('fk_idquestion', models.ForeignKey(blank=True, db_column='fk_idQuestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Question')),
                ('fk_informationitem', models.ForeignKey(blank=True, db_column='fk_Informationitem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Informationitem')),
                ('fk_module', models.ForeignKey(blank=True, db_column='fk_Module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobilemedias', to='core.Module')),
            ],
            options={
                'db_table': 'MobileMedia',
                'ordering': ['idmobilemedia'],
            },
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(blank=True, db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_idmodule',
            field=models.ForeignKey(blank=True, db_column='fk_idModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Module'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_informationitem',
            field=models.ForeignKey(blank=True, db_column='fk_idInformationItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructionalelements', to='core.Informationitem'),
        ),
        migrations.AddField(
            model_name='instructionalelement',
            name='fk_instructionalelementtype',
            field=models.ForeignKey(blank=True, db_column='fk_InstructionalElementType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Instrucelementtype'),
        ),
        migrations.AddField(
            model_name='informationitem',
            name='fk_informationitemtype',
            field=models.ForeignKey(db_column='fk_InformationItemType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationitemtypes', to='core.Informationitemtype'),
        ),
        migrations.AddField(
            model_name='concept',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(db_column='fk_idKnowledgeDomain', on_delete=django.db.models.deletion.CASCADE, to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='concept',
            name='fk_idmodule',
            field=models.ForeignKey(db_column='fk_idModule', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.Module'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idconcept',
            field=models.ForeignKey(db_column='fk_idConcept', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Concept'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idknowledgedomain',
            field=models.ForeignKey(db_column='fk_idKnowledgeDomain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Knowledgedomain'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='fk_idmodule',
            field=models.ForeignKey(db_column='fk_idModule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentparameter', to='core.Module'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='scopo',
            field=models.ForeignKey(db_column='scopo', on_delete=django.db.models.deletion.CASCADE, to='core.Scopo'),
        ),
        migrations.AddField(
            model_name='assessmentparameter',
            name='typethreshold',
            field=models.ForeignKey(db_column='typeThreshold', on_delete=django.db.models.deletion.CASCADE, to='core.Typethreshold'),
        ),
        migrations.CreateModel(
            name='Answersalternatives',
            fields=[
                ('idanswersalternatives', models.AutoField(db_column='idAnswersAlternatives', primary_key=True, serialize=False)),
                ('idobjanswer', models.CharField(blank=True, db_column='idObjAnswer', max_length=256, null=True)),
                ('answers', models.CharField(db_column='answers', max_length=256)),
                ('istrue', models.BooleanField(db_column='isTrue')),
                ('orderansweralternatives', models.BigIntegerField(blank=True, db_column='orderAnswerAlternatives', null=True)),
                ('fk_idquestion', models.ForeignKey(db_column='fk_idQuestion', on_delete=django.db.models.deletion.CASCADE, related_name='answersalternatives', to='core.Question')),
            ],
            options={
                'db_table': 'AnswersAlternatives',
                'ordering': ['orderansweralternatives'],
>>>>>>> 8a4d1bc5da85f232fc9afed6d358a7e45a92b863
            },
        ),
    ]
