# Generated by Django 3.0.6 on 2020-07-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answersalternatives',
            fields=[
                ('idanswersalternatives', models.AutoField(db_column='idAnswersAlternatives', primary_key=True, serialize=False)),
                ('idobjanswer', models.CharField(blank=True, db_column='idObjAnswer', max_length=256, null=True)),
                ('answers', models.CharField(db_column='answers', max_length=256)),
                ('istrue', models.BooleanField(db_column='isTrue')),
                ('orderansweralternatives', models.BigIntegerField(blank=True, db_column='orderAnswerAlternatives', null=True)),
            ],
            options={
                'db_table': 'AnswersAlternatives',
                'ordering': ['orderansweralternatives'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessmentparameter',
            fields=[
                ('idassessmentparameter', models.AutoField(db_column='idAssessmentParameter', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AssessmentParameter',
                'ordering': ['idassessmentparameter'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('idconcept', models.AutoField(db_column='idConcept', primary_key=True, serialize=False)),
                ('nameconcept', models.CharField(db_column='nameConcept', max_length=100)),
                ('fk_idconcept', models.BigIntegerField(blank=True, db_column='fk_idConcept', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'Concept',
                'ordering': ['idconcept'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informationitem',
            fields=[
                ('idinformationitem', models.AutoField(db_column='idInformationItem', primary_key=True, serialize=False)),
                ('nameinformationitem', models.CharField(blank=True, db_column='nameInformationItem', max_length=256, null=True)),
                ('descriptioninformationitem', models.TextField(blank=True, db_column='descriptionInformationItem', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'InformationItem',
                'ordering': ['idinformationitem'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informationitemtype',
            fields=[
                ('idinformationitemtype', models.AutoField(db_column='idInformationItemType', primary_key=True, serialize=False)),
                ('nameinformationitemtype', models.CharField(db_column='nameInformationItemType', max_length=256)),
            ],
            options={
                'db_table': 'InformationItemType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrucelementtype',
            fields=[
                ('idinstrucelementtype', models.AutoField(db_column='idInstrucElementType', primary_key=True, serialize=False)),
                ('nameinstrucelementtype', models.CharField(db_column='nameInstrucElementType', max_length=256)),
                ('idcategory', models.BigIntegerField(blank=True, db_column='idCategory', null=True)),
            ],
            options={
                'db_table': 'InstrucElementType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructionalelement',
            fields=[
                ('idinstructionalelement', models.AutoField(db_column='idInstructionalElement', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='label', max_length=256)),
                ('memberamount', models.BigIntegerField(blank=True, db_column='memberAmount', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'InstructionalElement',
                'ordering': ['idinstructionalelement'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Knowledgedomain',
            fields=[
                ('idknowledgedomain', models.AutoField(db_column='idKnowledgeDomain', primary_key=True, serialize=False)),
                ('nameknowledgedomain', models.CharField(db_column='nameKnowledgeDomain', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('lastversion', models.CharField(blank=True, db_column='lastVersion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'KnowledgeDomain',
                'ordering': ['idknowledgedomain'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediatype',
            fields=[
                ('idmediatype', models.AutoField(db_column='idMediaType', primary_key=True, serialize=False)),
                ('namemediatype', models.CharField(blank=True, db_column='nameMediaType', max_length=256)),
            ],
            options={
                'db_table': 'MediaType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobilemedia',
            fields=[
                ('idmobilemedia', models.AutoField(db_column='idMobileMedia', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', max_length=256, null=True)),
                ('difficultyLevel', models.IntegerField(blank=True, db_column='difficultyLevel', null=True)),
                ('learningStyle', models.IntegerField(blank=True, db_column='learningStyle', null=True)),
                ('path', models.CharField(blank=True, db_column='path', max_length=256, null=True)),
                ('namefile', models.CharField(blank=True, db_column='nameFile', max_length=256, null=True)),
                ('resolution', models.CharField(blank=True, db_column='resolution', max_length=256, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('time', models.CharField(blank=True, db_column='time', max_length=256, null=True)),
                ('textfull', models.TextField(blank=True, db_column='textFull', null=True)),
                ('textshort', models.TextField(blank=True, db_column='textShort', null=True)),
                ('urllink', models.CharField(blank=True, db_column='url', max_length=256, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'MobileMedia',
                'ordering': ['idmobilemedia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idmodule', models.AutoField(db_column='idModule', primary_key=True, serialize=False)),
                ('namemodule', models.CharField(db_column='nameModule', max_length=100)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=100, null=True)),
                ('visible', models.BooleanField(blank=True, db_column='visible', default=True, null=True)),
            ],
            options={
                'db_table': 'Module',
                'ordering': ['idmodule'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phaseprocedure',
            fields=[
                ('idphaseprocedure', models.AutoField(db_column='idPhaseProcedure', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='order')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'PhaseProcedure',
                'ordering': ['order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorknowledge',
            fields=[
                ('idpriorknowledge', models.AutoField(db_column='idPriorKnowledge', primary_key=True, serialize=False)),
                ('namepriorknowledge', models.CharField(db_column='namePriorKnowledge', max_length=256)),
            ],
            options={
                'db_table': 'PriorKnowledge',
                'ordering': ['idpriorknowledge'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorlevel',
            fields=[
                ('idpriorlevel', models.AutoField(db_column='idPriorLevel', primary_key=True, serialize=False)),
                ('typepriorlevel', models.CharField(db_column='typePriorLevel', max_length=256)),
            ],
            options={
                'db_table': 'PriorLevel',
                'ordering': ['idpriorlevel'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.AutoField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('descriptionquestion', models.TextField(db_column='descriptionQuestion')),
                ('orderquestion', models.IntegerField(blank=True, db_column='orderQuestion', null=True)),
            ],
            options={
                'db_table': 'Question',
                'ordering': ['orderquestion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('idquestiontype', models.AutoField(db_column='idQuestionType', primary_key=True, serialize=False)),
                ('namequestiontype', models.CharField(db_column='nameQuestionType', max_length=256)),
            ],
            options={
                'db_table': 'QuestionType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('idrange', models.AutoField(db_column='idRange', primary_key=True, serialize=False)),
                ('namerange', models.CharField(db_column='nameRange', max_length=256)),
                ('initialvalue', models.IntegerField(db_column='initialValue')),
                ('limitvalue', models.IntegerField(db_column='limitValue')),
            ],
            options={
                'db_table': 'Range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idreference', models.AutoField(db_column='idReference', primary_key=True, serialize=False)),
                ('namereference', models.CharField(blank=True, db_column='nameReference', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencetype',
            fields=[
                ('idreferencetype', models.AutoField(db_column='idReferenceType', primary_key=True, serialize=False)),
                ('namererefencetype', models.CharField(db_column='nameRerefenceType', max_length=256)),
            ],
            options={
                'db_table': 'Referencetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resolutionquestion',
            fields=[
                ('idresolutionquestion', models.AutoField(db_column='idResolutionQuestion', primary_key=True, serialize=False)),
                ('correctitem', models.TextField(blank=True, db_column='correctItem', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='correctAnswer', null=True)),
            ],
            options={
                'db_table': 'ResolutionQuestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scopo',
            fields=[
                ('idscopo', models.AutoField(db_column='idScopo', primary_key=True, serialize=False)),
                ('typescopo', models.CharField(db_column='typeScopo', max_length=256)),
            ],
            options={
                'db_table': 'Scopo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('idsingle', models.AutoField(db_column='idSingle', primary_key=True, serialize=False)),
                ('threshold', models.CharField(blank=True, db_column='threshold', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Single',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typethreshold',
            fields=[
                ('idtypethreshold', models.AutoField(db_column='idTypeThreshold', primary_key=True, serialize=False)),
                ('nametypethreshold', models.CharField(db_column='nameTypeThreshold', max_length=256)),
            ],
            options={
                'db_table': 'TypeThreshold',
                'managed': False,
            },
        ),
    ]
