# Generated by Django 3.0.6 on 2020-08-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200817_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
