# Generated by Django 3.0.6 on 2020-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200817_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='path',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
