# Generated by Django 3.0.6 on 2020-08-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200804_2230'),
        ('core', '0007_auto_20200817_2052'),
    ]

    operations = [
    ]
