# Generated by Django 3.0.6 on 2020-10-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20200827_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='mobilemedia',
            name='fk_iduser',
            field=models.ForeignKey(blank=True, db_column='fk_idUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileimage', to=settings.AUTH_USER_MODEL),
        ),
    ]
