# Generated by Django 3.0.6 on 2020-05-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answersalternatives',
            fields=[
                ('idanswersalternatives', models.BigIntegerField(db_column='idAnswersAlternatives', primary_key=True, serialize=False)),
                ('idobjanswer', models.CharField(blank=True, db_column='idObjAnswer', max_length=256, null=True)),
                ('answers', models.CharField(blank=True, max_length=256, null=True)),
                ('istrue', models.BooleanField(blank=True, db_column='isTrue', null=True)),
            ],
            options={
                'db_table': 'AnswersAlternatives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('idconcept', models.BigIntegerField(db_column='idConcept', primary_key=True, serialize=False)),
                ('nameconcept', models.CharField(db_column='nameConcept', max_length=256)),
                ('fk_idconcept', models.BigIntegerField(blank=True, db_column='fk_idConcept', null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informationitem',
            fields=[
                ('idinformationitem', models.BigIntegerField(db_column='idInformationItem', primary_key=True, serialize=False)),
                ('nameinformationitem', models.CharField(blank=True, db_column='nameInformationItem', max_length=256, null=True)),
            ],
            options={
                'db_table': 'InformationItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informationitemtype',
            fields=[
                ('idinformationitemtype', models.IntegerField(db_column='idInformationItemType', primary_key=True, serialize=False)),
                ('nameinformationitem', models.CharField(db_column='nameInformationItem', max_length=256)),
            ],
            options={
                'db_table': 'InformationItemType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrctionalelement',
            fields=[
                ('idinstructionalelement', models.BigIntegerField(db_column='idInstructionalElement', primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'InstrctionalElement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructionalelementtype',
            fields=[
                ('idinstrucelementtype', models.BigIntegerField(db_column='idInstrucElementType', primary_key=True, serialize=False)),
                ('nameinstrucelementtype', models.CharField(db_column='nameInstrucElementType', max_length=256)),
                ('idcategory', models.BigIntegerField(blank=True, db_column='idCategory', null=True)),
            ],
            options={
                'db_table': 'InstructionalElementType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Knowledgedomain',
            fields=[
                ('idknowledgedomain', models.IntegerField(db_column='idKnowledgeDomain', primary_key=True, serialize=False)),
                ('nameknowledgedomain', models.CharField(blank=True, db_column='nameKnowledgeDomain', max_length=45, null=True)),
                ('subtitle', models.CharField(blank=True, db_column='subTitle', max_length=45, null=True)),
                ('lastversion', models.CharField(blank=True, db_column='lastVersion', max_length=45, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'KnowledgeDomain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediatype',
            fields=[
                ('idmediatype', models.IntegerField(db_column='idMediaType', primary_key=True, serialize=False)),
                ('namemedia', models.CharField(db_column='nameMedia', max_length=256)),
            ],
            options={
                'db_table': 'MediaType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobilemedia',
            fields=[
                ('idmobilemedia', models.BigIntegerField(db_column='idMobileMedia', primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('fk_informationitem', models.BigIntegerField(blank=True, db_column='fk_Informationitem', null=True)),
                ('fk_idmediatype', models.IntegerField(blank=True, db_column='fk_idMediaType', null=True)),
                ('fk_idknowledgedomain', models.BigIntegerField(blank=True, db_column='fk_idKnowledgeDomain', null=True)),
                ('fk_idinstructionalelement', models.BigIntegerField(blank=True, db_column='fk_idInstructionalElement', null=True)),
                ('fk_idconcept', models.BigIntegerField(blank=True, db_column='fk_idConcept', null=True)),
            ],
            options={
                'db_table': 'MobileMedia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idmodule', models.BigIntegerField(db_column='idModule', primary_key=True, serialize=False)),
                ('namemodule', models.CharField(db_column='nameModule', max_length=256)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phaseprocedure',
            fields=[
                ('idphaseprocedure', models.IntegerField(db_column='idPhaseProcedure', primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'PhaseProcedure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.BigIntegerField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('orderquestion', models.CharField(blank=True, db_column='orderQuestion', max_length=256, null=True)),
                ('typequestion', models.IntegerField(blank=True, db_column='typeQuestion', null=True)),
                ('fk_idinstrctionalelement', models.BigIntegerField(blank=True, db_column='fk_idInstrctionalElement', null=True)),
            ],
            options={
                'db_table': 'Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idreference', models.BigIntegerField(db_column='idReference', primary_key=True, serialize=False)),
                ('namereference', models.CharField(blank=True, db_column='nameReference', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencetype',
            fields=[
                ('idreferencetype', models.BigIntegerField(db_column='idReferenceType', primary_key=True, serialize=False)),
                ('namererefencetype', models.CharField(db_column='nameRerefenceType', max_length=256)),
            ],
            options={
                'db_table': 'Referencetype',
                'managed': False,
            },
        ),
    ]
