# Generated by Django 3.0.6 on 2020-05-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'managed': False, 'ordering': ['idmodule']},
        ),
    ]
