# Generated by Django 3.0.6 on 2020-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200527_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructionalelement',
            fields=[
                ('idinstructionalelement', models.BigIntegerField(db_column='idInstructionalElement', primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'InstructionalElement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Instrctionalelement',
        ),
    ]
