# Generated by Django 3.0.6 on 2020-05-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'managed': False, 'ordering': ['idconcept']},
        ),
    ]
